# Generated by Django 6.0.7 on 2026-08-18 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_product_default_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate'),
        ),
    ]
