# Generated by Django 6.0.7 on 2026-08-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_product_default_price_and_more'),
        ('base', '0055_alter_taxrule_rate_and_more'),
    ]

    operations = [
    ]
