# Generated by Django 6.0.7 on 2026-08-17 21:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_emailqueue_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueuefilter',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='emailqueuefilter',
            name='recipients',
            field=models.CharField(blank=True, choices=[('orders', 'Orders'), ('attendees', 'Attendees'), ('both', 'Both'), ('individual', 'Individual')], default='orders', max_length=10),
        ),
    ]
